In [ ]:
#variable
a=10
print("I am",a,"years old")

I am 10 years old


1
(4,)
[1 2 3 4]
2
(2, 3)
[[1 2 3]
 [4 5 6]]
3
(2, 3, 3)
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[3 2 1]
  [6 5 4]
  [9 8 7]]]


[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np
B=np.array([1,2,3,],[4,5,6])
print(B.ndim)
print(B.shape)

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [ ]:
#LC
#NEWLIST=[(st of if)if (cond) else (st of else)for]
l1=[1,2,3,4,5,6,7,8,9]
res=[i*i if i>5 else 'x' for i in l1]
print(res)

['x', 'x', 'x', 'x', 'x', 36, 49, 64, 81]


In [ ]:
#take the salary from the user if the salary is less 50000-10%tax,else 15%
salary=[]
salary=int(input("Enter salary:"))
res=[salary-(salary*0.1 if salary<50000 else salary-(salary*0.15))]
print(res)

Enter salary:55000
[8250.0]


In [ ]:
#take the salary from the user if the salary is less 50000-10%tax,else 15%
salary=[78000,50400,34000,23000,14000]
res=[i-(i*0.1) if i<50000 else i-(i*0.15) for i in salary]
print(res)

[66300.0, 42840.0, 30600.0, 20700.0, 12600.0]


In [ ]:
#create
d={1:'a',2:"b",3:'c',4:1,5:2,6:3}
print(d)
print(d.keys())
print(d.values())
print(d[3])

{1: 'a', 2: 'b', 3: 'c', 4: 1, 5: 2, 6: 3}
dict_keys([1, 2, 3, 4, 5, 6])
dict_values(['a', 'b', 'c', 1, 2, 3])
c


In [ ]:
d2={"dept":"cse","details":{"year":"II","sec":"D","count":71}}
print("department is:",d2["dept"])
print("section is:",d2["details"]["sec"])
print("count is:",d2["details"]["count"])


department is: cse
section is: D
count is: 71


In [ ]:
l1=['a','b','c']
l2=[1,2,3]
l3=(zip(l1,l2))
print(l3)

In [ ]:
#Arthemetic oprs between two numbers
a=int(input("enter first num"))
b=int(input("enter secvond num"))
print('sum:',a+b)
print('Dif:',a-b)
print('prod:',a*b)
print('Quot:',a/b)
print('pow:',a**b)
print('Rem:',a%b)
print('Floor:',a//b)


enter first num2
enter secvond num4
sum: 6
Dif: -2
prod: 8
Quot: 0.5
pow: 16
Rem: 2
Floor: 0


In [ ]:
#Take salary from  the user,if the salary is more than 50,000 there is 10% tax reduction.Print his final salary
salary=int(input("Enter the salary:"))
if salary>=50000:
  a=salary-(salary*0.1)
  print(a)
else:
 print("salary is less than 50000")


Enter the salary:55000
49500.0


In [ ]:
#Get the salary from the user if the salary is more than or equal to 50000 then apply 10%tax dedection,if the salary is less than 50000 then apply 5%tax deduction,if it is more than 70000 then apply 12%tax deduction.If the salary exceeds 1lakh,print you are promoted to next level
salary=int(input("Enter the salary:"))
if salary>=50000:
     a=salary-(salary*0.1)
     print(a)
elif salary<50000:
       b=salary-(salary*0.05)
       print(b)
elif salary>70000:
    c=salary-(salary*0.12)
    print(c)
elif salary>100000:
    print("you are promoted")

Enter the salary:55000
49500.0


In [ ]:
a=range(1,11)
print(a)

range(1, 11)


In [ ]:
n=int(input("enter a number:"))
for i in range(1,11):
 print(n,"*",i,"=",i*n)

enter a number:8
8 * 1 = 8
8 * 2 = 16
8 * 3 = 24
8 * 4 = 32
8 * 5 = 40
8 * 6 = 48
8 * 7 = 56
8 * 8 = 64
8 * 9 = 72
8 * 10 = 80


In [ ]:
n=int(input("enter a number:"))
i=1
while(i<=10):
  print(n,"*",i,"=",i*n)
  i=i+1



enter a number:9
9 * 1 = 9
9 * 2 = 18
9 * 3 = 27
9 * 4 = 36
9 * 5 = 45
9 * 6 = 54
9 * 7 = 63
9 * 8 = 72
9 * 9 = 81
9 * 10 = 90


In [ ]:
#mutable
l1=[1,'a','b','c',"vasavi"]
print(l1)
l1.insert(4,"college")
print(l1)
l2=["apple"]
l1.extend(l2)
print(l1)





SyntaxError: invalid syntax (<ipython-input-64-45a577925176>, line 2)

In [ ]:
#create a list of 10 integers elements ,print their squares and save these squares in new list
l1=[1,2,3,4,5,6,7,8,9,0]
l2=[i*i for i in l1]
print(l2)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 0]


In [ ]:
l1=[1,2,3,4,5,6,7,8,9,0]
l2=[i*i for i in l1 if i<5]
print(l2)



[1, 4, 9, 16, 0]


In [ ]:
import numpy as np
A=np.array([1,2,3,4])#1D
print(A.ndim)
print(A.shape)
print(A)
B=np.array([[1,2,3,],[4,5,6]])#2D
#colomns=elements in each row
print(B.ndim)
print(B.shape)
print(B)
c=np.array([[[1,2,3,],[4,5,6],[7,8,9]],[[3,2,1],[6,5,4],[9,8,7]]])#3D
print(c.ndim)
print(c.shape)
print(c)

1
(4,)
[1 2 3 4]
2
(2, 3)
[[1 2 3]
 [4 5 6]]
3
(2, 3, 3)
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[3 2 1]
  [6 5 4]
  [9 8 7]]]


In [ ]:
a=np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
a=np.zeros((2,3,3))#another way to create arrays
print(a)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
a=np.arange(1,10)
print(a)
print(type(a))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [ ]:
a=np.arange(1,10,2)#start,stop,step
print(a)
print(type(a))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [ ]:
#Print all the numbers that are divisible by 8 using arange function between 1 and 1000
a=np.arange(8,1001,8)
print(a)

[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]


In [ ]:
a=np.linspace(48,59,10)#linspace=spliting arange into n numbers with comman differences
print(a)

[48.         49.22222222 50.44444444 51.66666667 52.88888889 54.11111111
 55.33333333 56.55555556 57.77777778 59.        ]


In [ ]:
#sort()
a=[1,8,6,4]
a.sort()
print(a)

[1, 4, 6, 8]


In [ ]:
#sorted(requires a new storage location)
a=[1,4,3,6,3]
b=sorted(a)
print(a)
print(b)

[1, 4, 3, 6, 3]
[1, 3, 3, 4, 6]


In [1]:
a=('ajay','raj','prem')
b=(1,1.3,'ravi')
print(a+b)

('ajay', 'raj', 'prem', 1, 1.3, 'ravi')


In [2]:
a=('thor','loki')
b=('hulk','peter')
print(a*5)
print(b*3)

('thor', 'loki', 'thor', 'loki', 'thor', 'loki', 'thor', 'loki', 'thor', 'loki')
('hulk', 'peter', 'hulk', 'peter', 'hulk', 'peter')


In [3]:
t=(54,66,74,81,20,11,13)
print(max(t))

81


In [4]:
#removing element from tuple
t=('a','b','c','d')
l=list(t)
print(l)
l.remove('c')
t=tuple(l)
print(t)

['a', 'b', 'c', 'd']
('a', 'b', 'd')


In [5]:
#add element to tuple
t=('a','b','c','d')
l=list(t)
print(l)
l.append('e')
t=tuple(l)
print(t)

['a', 'b', 'c', 'd']
('a', 'b', 'c', 'd', 'e')


In [6]:
s={'data','analysis','python'}
s.remove('analysis')
print(s)

{'data', 'python'}


In [7]:
s={'iron','cobalt','nickel','silver'}
s.add('gold')
print(s)

{'nickel', 'silver', 'iron', 'gold', 'cobalt'}


In [8]:
s={11,2,4,3}
print(type(s))

<class 'set'>
