In [ ]:
import numpy as np


SyntaxError: invalid syntax (<ipython-input-2-bf28020b95a0>, line 1)

In [2]:
import numpy as np

In [ ]:
a=np.arange(1,13).reshape(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
a=np.linspace(2,8,10).reshape(5,2)#5rows,2columns
print(a)

[[2.         2.66666667]
 [3.33333333 4.        ]
 [4.66666667 5.33333333]
 [6.         6.66666667]
 [7.33333333 8.        ]]


In [ ]:
b=np.array([49,45,32,11,12,13,54,43]).reshape(2,2,2)#normal array can be reshaped
print(b)

[[[49 45]
  [32 11]]

 [[12 13]
  [54 43]]]


In [ ]:
b=np.array([49,45,32,11,12,13,54,43])
b.resize(2,2,2)#changes the shape of original array
print(b)

[[[49 45]
  [32 11]]

 [[12 13]
  [54 43]]]


In [ ]:
a=np.array([34,56,78,90])
b=np.array([7,9,3,12])#list will throw an error while arrays iterate themselves
print(a-b)

[27 47 75 78]


In [ ]:
#ARRAY OPERATIONS:-
a=np.array([1,2,3,4])
b=np.array([4,3,2,1])

print(a)
print("****")
print(b)
print("****")
print(a+b)


[1 2 3 4]
****
[4 3 2 1]
****
[5 5 5 5]


In [ ]:
a=np.array([1,2,3,4]).reshape(2,2)
b=np.array([4,3,2,1]).reshape(2,2)
print(a)
print("****")
print(b)
print("****")
print(a*b)


[[1 2]
 [3 4]]
****
[[4 3]
 [2 1]]
****
[[4 6]
 [6 4]]


In [ ]:
a=np.array([1,2,3,4]).reshape(2,2)
b=np.array([4,3,2,1]).reshape(2,2)
print(a)
print("****")
print(b)
print("****")
print(a@b)#matrix multiplication

[[1 2]
 [3 4]]
****
[[4 3]
 [2 1]]
****
[[ 8  5]
 [20 13]]


In [ ]:
a=np.array([1,2,3,4]).reshape(2,2)
b=np.array([4,3,2,1]).reshape(2,2)
print(a)
print("****")
print(b)
print("****")
print(a.dot(b))#matrix multiplication

[[1 2]
 [3 4]]
****
[[4 3]
 [2 1]]
****
[[ 8  5]
 [20 13]]


In [ ]:
a=np.array([1,2,3,4])
print(a.max())#only works for numeric data types :integers and float ,but not for string
print(a.min())


4
1


In [ ]:
a=np.array([4,2,3,1]).reshape(2,2)

print(a)
print("****")
print(a.max(axis=0))#coloum wise large elements
print("****")
print(a.max(axis=1))#row wise large elements

[[4 2]
 [3 1]]
****
[4 2]
****
[4 3]


In [ ]:
a=np.array([4,2,3,1]).reshape(2,2)

print(a)
print("****")
print(a.min(axis=0))#coloum wise minimum elements
print("****")
print(a.min(axis=1))#row wise minimum elements

[[4 2]
 [3 1]]
****
[3 1]
****
[2 1]


In [ ]:
a=np.array([1,2,3,4]).reshape(2,2)
b=np.array([4,3,2,1]).reshape(2,2)
print(a)
print("****")
print(b)
print("****")
print(np.stack((a,b),axis=0))#joining array horizontally

[[1 2]
 [3 4]]
****
[[4 3]
 [2 1]]
****
[[[1 2]
  [3 4]]

 [[4 3]
  [2 1]]]


In [ ]:
a=np.array([1,2,3,4]).reshape(2,2)
b=np.array([4,3,2,1]).reshape(2,2)
print(a)
print("****")
print(b)
print("****")
print(np.stack((a,b),axis=1))

[[1 2]
 [3 4]]
****
[[4 3]
 [2 1]]
****
[[[1 2]
  [4 3]]

 [[3 4]
  [2 1]]]


In [ ]:
a=np.arange(30).reshape(2,3,5)

print(a)
print("after dstack")
print(np.dstack(a))



[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
after dstack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
a=np.arange(18).reshape(6,3)

print(a)
print("****")
print("After splitting")
np.vsplit(a,3)#arrayname,no.of pieces)--if no of pieces/no.of rows is possibleder345456

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
****
After splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [ ]:
a=np.arange(18).reshape(6,3)

print(a)
print("****")
print("After splitting")
np.hsplit(a,3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
****
After splitting


[array([[ 0],
        [ 3],
        [ 6],
        [ 9],
        [12],
        [15]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]])]

In [ ]:
a=np.arange(18).reshape(6,3)

print(a)
print("****")
print("After splitting")
np.vsplit(a,(3,4))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
****
After splitting


[array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [ ]:
a=np.arange(18).reshape(6,3)

print(a)
print("****")
print("After splitting")
np.hsplit(a,(2,5))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
****
After splitting


[array([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10],
        [12, 13],
        [15, 16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([], shape=(6, 0), dtype=int64)]

In [ ]:
a=np.array([11,63,43,56]).reshape(2,2)

print(a)
print("****")
print(a.argmax(axis=0))#gives max,min value's position respectively



[[11 63]
 [43 56]]
****
[1 0]


In [ ]:
a=np.array([11,63,43,56]).reshape(2,2)

print(a)
print("****")
print(a.argmax(axis=1))

[[11 63]
 [43 56]]
****
[1 1]


In [ ]:
a=np.array([11,63,43,56]).reshape(2,2)

print(a)
print("****")
print(a.argmin(axis=0))#gives min,max value's position respectively

[[11 63]
 [43 56]]
****
[0 1]


In [ ]:
#STATISTICTS(mean,median,standard diviation,variance)
a=np.array([1,2,3,4,5])
print("mean:",np.mean(a))
print("median:",np.median(a))
print("variance:",np.var(a))
print("standard dev:",np.std(a))

mean: 3.0
median: 3.0
variance: 2.0
standard dev: 1.4142135623730951


In [ ]:
a=np.pi#radians
print(a)

a=np.rad2deg(a)#degree
print(a)

3.141592653589793
180.0


In [ ]:
a=np.array([np.pi/4,np.pi/3,np.pi/2,np.pi])
print(a)

a=np.array([np.pi/4,np.pi/3,np.pi/2,np.pi])
print(np.rad2deg(a))


[0.78539816 1.04719755 1.57079633 3.14159265]
[ 45.  60.  90. 180.]


In [ ]:
a=np.array([1,30,45,60,90,120,180])
print(np.deg2rad(a))

[0.01745329 0.52359878 0.78539816 1.04719755 1.57079633 2.0943951
 3.14159265]


In [ ]:
a=np.array([30,45,60,90,120,180])
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))
print("****")
print(np.arcsin(1))
print(np.arccos(1))
print(np.arctan(1))

[-0.98803162  0.85090352 -0.30481062  0.89399666  0.58061118 -0.80115264]
[ 0.15425145  0.52532199 -0.95241298 -0.44807362  0.81418097 -0.59846007]
[-6.4053312   1.61977519  0.32004039 -1.99520041  0.71312301  1.33869021]
****
1.5707963267948966
0.0
0.7853981633974483


In [ ]:
a=np.array([10,22,11,2,33,45])
print(np.where(a==11))#searching array element

(array([2]),)


In [ ]:
a=np.array([10,22,11,2,33,45])
print(np.where(a%2==0))#even

(array([0, 1, 3]),)


In [ ]:
a=np.array([10,22,11,2,33,45])
print(np.where(a>11))#greater than n

(array([1, 4, 5]),)


In [4]:
a=np.array([1,2,3,4])
print(np.searchsorted(a,3))

2


In [12]:
a=np.array([1,2,3,4,5])
b=np.array([9,8,7,6,2])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.divide(a,b))
print(np.mod(a,b))
print(np.diff(a))
print(np.diff(b))
print(np.sort(b))
print(np.union1d(a,b))
print(np.intersect1d(a,b))

[10 10 10 10  7]
[-8 -6 -4 -2  3]
[0.11111111 0.25       0.42857143 0.66666667 2.5       ]
[1 2 3 4 1]
[1 1 1 1]
[-1 -1 -1 -4]
[2 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[2]


In [15]:
#Truncate-removes decimals
a=np.trunc([-3.123,3.6667])
print(a)

[-3.  3.]


In [16]:
#Rounding
a=np.round([-3.123,3.6667])
print(a)


[-3.  4.]


In [17]:
a=np.fix([-3.123,3.6667])
print(a)

[-3.  3.]


In [18]:
#floor-gives the nearest least value
 a=np.floor([-3.123,3.6667])
print(a)

[-4.  3.]


In [19]:
#ceil-gives the nearest hightest
a=np.ceil([-3.123,3.6667])
print(a)

[-3.  4.]


In [20]:
#cummulative sum
a=np.array([1,2,33,4])

print(np.cumsum(a))


[ 1  3 36 40]


In [21]:
#cumulative prodact
a=np.array([1,2,33,4])

print(np.cumprod(a))


[  1   2  66 264]


In [30]:


print(np.lcm(12,4))#works only for 2 numbetrs

a=np.array([2,4,6,9])#works for n numbers
print(np.lcm.reduce(a))

12
36


In [31]:
a=np.array([[1,2],[3,4]])
print(np.linalg.inv(a))#linearalgebra

[[-2.   1. ]
 [ 1.5 -0.5]]


In [37]:
from numpy import random as rd

In [39]:
a=rd.rand(10)
print(a)

[0.43746229 0.84233461 0.89958483 0.99937749 0.71189097 0.28596924
 0.50267328 0.41905139 0.89862514 0.1754112 ]


In [41]:
a=rd.randint(10,size=2)
print(a)

[2 0]


In [42]:
a=rd.randint(50,size=6)
print(a)

[15 42 49 46 21 33]


In [43]:
a=rd.randint(50,size=(2,3))#size=shape
print(a)

[[13  5 20]
 [ 5 32 28]]


In [44]:
a=np.array([12,1,21,3])
b=np.array([11,21,33,14])#12x11+1x21....=888
print(np.inner(a,b))

888


In [46]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])#a1xbn,a2xbn....
print(np.outer(a,b))

[[ 5  6  7  8]
 [10 12 14 16]
 [15 18 21 24]
 [20 24 28 32]]


In [53]:
a=np.array([1,2,3])
b=np.array([5,6,7])
print(np.cross(a,b)) #like determinant in matrix

[-4  8 -4]
